changelog:
  exclude:
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"

