name: setup-node-pnpm
description: Set up Node.js (from .nvmrc), activate pinned pnpm via Corepack, and optionally install deps (cached).
inputs:
  install:
    description: Run pnpm install after setup.
    required: false
    default: "true"
runs:
  using: composite
  steps:
    # IMPORTANT: Corepack must enable pnpm BEFORE actions/setup-node runs with cache: pnpm
    # because setup-node needs to run `pnpm store path` to determine the cache directory
    - name: Enable Corepack and activate pinned pnpm
      shell: bash
      run: |
        set -euo pipefail
        corepack enable
        # Read exact packageManager (e.g., pnpm@10.28.0) from package.json and activate it
        PM=$(node -p "require('./package.json').packageManager")
        if [[ -z "$PM" ]]; then
          echo "package.json:packageManager is empty; expected an exact pnpm version" >&2
          exit 1
        fi
        echo "Activating $PM via Corepack"
        if corepack prepare "$PM" --activate; then
          echo "Corepack prepared $PM"
        else
          echo "Corepack prepare failed, falling back to npm global install" >&2
          npm install -g "${PM%@*}"
        fi
        pnpm --version
        EXPECTED_VERSION_RAW="${PM#*@}"
        EXPECTED_VERSION="${EXPECTED_VERSION_RAW%%+*}"
        ACTUAL_VERSION=$(pnpm --version)
        if [[ "$ACTUAL_VERSION" != "$EXPECTED_VERSION" ]]; then
          echo "::warning::pnpm version mismatch: expected $EXPECTED_VERSION, got $ACTUAL_VERSION"
        fi

    - name: Setup Node.js from .nvmrc (with pnpm cache)
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
